spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://172.28.7.32:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  instance:
    hostname: 172.28.7.46
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.28.7.46:8761/eureka/,http://172.28.7.46:8861/eureka/,http://172.28.7.46:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
