spring:
  application:
    name: itoken-client
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info