spring:
  application:
    name: itoken-admin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: *

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/euraka/