spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/

zool:
  routes:
    api-a:
      path: /api/a/**
      serviceId: itoken-client

hystrix:
  command:
    itoken-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

itoken-server:
  ribbon:
    ReadTimeout : 3000
    ConnectTimeout : 3000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info