spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://172.28.7.32:8084
  zipkin:
    base-url: http://localhost:9411

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8861

eureka:
  instance:
    hostname: itoken-eureka-2
    ipAddress: 172.28.7.46
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://itoken-eureka-1:8761/eureka/,http://itoken-eureka-3:8961/eureka/
