spring:
  application:
    name: itoken-admin
  boot:
    admin:
      client:
        url: http://172.28.7.32:8084

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

eureka:
  instance:
    prefer-ip-address: true
    ipAddress: 172.28.7.32
    hostname: itoken-admin
    instance-id: ${eureka.instance.ip-address}:${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://172.28.7.46:8761/eureka/,http://172.28.7.46:8861/eureka/,http://172.28.7.46:8961/eureka/
