spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://172.28.7.32:8084
  zipkin:
    base-url: http://localhost:9411
  client:
    hostname: itoken-eureka-1
    ip-address: ${HOST}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.cloud.client.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.cloud.client.hostname}:8861/eureka/,http://${spring.cloud.client.hostname}:8961/eureka/
