spring:
  application:
    name: itoken-server
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka/

server:
  port: 8762

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info